image:
  repository: docker.io/brandawg93/peanut
  tag: 5.20.0@sha256:cc393cb30e6a632edad423eaddd419f0dcc85fee3cb5cef1e0e266bfc27e3b08
  pullPolicy: IfNotPresent
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10688
portal:
  open:
    enabled: true
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            NUT_HOST: "localhost"
            NUT_PORT: 3493
            USERNAME: ""
            PASSWORD: ""
            WEB_PORT: "{{ .Values.service.main.ports.main.port }}"
