image:
  repository: ghcr.io/ellite/wallos
  tag: 2.44.1@sha256:630cfabffb63ea86ef9e52bd13d87c95d6a0379c0325148c9a8a3094d36f4f46
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 8282
        protocol: tcp
        targetPort: 80

persistence:
  database:
    enabled: true
    mountPath: "/var/www/html/db"
  logos:
    enabled: true
    mountPath: "/var/www/html/images/uploads/logos"

portal:
  open:
    enabled: true
