image:
  repository: docker.io/sirfragalot/hyperion.ng
  tag: 2.1.1@sha256:e8aeec950b4b2a310c4e99566d0c76594fcd1a5d49b836f0d78680d189d6ae5c
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10065
        targetPort: 8090
  jsonservice:
    enabled: true
    ports:
      jsonservice:
        enabled: true
        port: 19444
        targetPort: 19444
  protobufservice:
    enabled: true
    ports:
      protobufservice:
        enabled: true
        port: 19445
        targetPort: 19445
  boblightservice:
    enabled: true
    ports:
      boblightservice:
        enabled: true
        port: 19333
        targetPort: 19333
persistence:
  config:
    enabled: true
    mountPath: "/root/.hyperion"
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
