image:
  repository: docker.io/acockburn/appdaemon
  pullPolicy: IfNotPresent
  tag: 4.5.0@sha256:0b76b955254a2e8f4eaad6c591a21ca68bfba93a3932c80cce72f1e9672adfa3
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 5050
        protocol: http
        targetPort: 5050
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env:
            DASH_URL: "http://$HOSTNAME:5050"
            HA_URL: ""
            LATITUDE: 46
            LONGITUDE: -94
            ELEVATION: 1217
            TIMEZONE: "{{ .Values.TZ }}"
            TOKEN: "REPLACETHIS"
persistence:
  conf:
    enabled: true
    mountPath: /conf
portal:
  open:
    enabled: true
