image:
  repository: ghcr.io/wizarrrr/wizarr
  pullPolicy: IfNotPresent
  tag: v2025.9.0@sha256:eadd073b2e59c4023b2b96643063e1a094068f0013bf6f771e4c7d07b9a81f2d
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 5690
        port: 10596
securityContext:
  container:
    runAsUser: 0
    runAsGroup: 0
    runAsNonRoot: false
    readOnlyRootFilesystem: false
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: "/"
              type: http
            readiness:
              path: "/"
              type: http
            startup:
              type: tcp
          env:
            DISABLE_BUILTIN_AUTH: false
persistence:
  database:
    enabled: true
    mountPath: /data/database
  varrun:
    enabled: false
    type: emptyDir
    mountPath: /var/run
  nginxrun:
    enabled: true
    type: emptyDir
    mountPath: /run/nginx
portal:
  open:
    enabled: true
