image:
  repository: docker.io/metabase/metabase
  pullPolicy: IfNotPresent
  tag: v0.57.9@sha256:b3cb5a3f4a9536ce9432b1eb9409a38bd9ba2b208e96b066a985d906bd7e3ace
service:
  main:
    ports:
      main:
        protocol: http
        port: 13030
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            MB_JETTY_PORT: "{{ .Values.service.main.ports.main.port }}"
            JAVA_TIMEZONE: "{{ .Values.TZ }}"
            MB_DB_TYPE: "postgres"
            MB_DB_USER: "{{ .Values.cnpg.main.user }}"
            MB_DB_DBNAME: "{{ .Values.cnpg.main.database }}"
            MB_DB_PORT: 5432
            MB_DB_HOST:
              secretKeyRef:
                name: cnpg-main-urls
                key: host
            MB_DB_PASS:
              secretKeyRef:
                name: cnpg-main-user
                key: password
persistence:
  plugins:
    enabled: true
    mountPath: "/plugins"
# Enabled postgres
cnpg:
  main:
    enabled: true
    user: metabase
    database: metabase
portal:
  open:
    enabled: true
