image:
  pullPolicy: IfNotPresent
  repository: docker.io/bobbintb/docker-rmlint-unraid
  tag: latest@sha256:cf10b25c12a3f918ec4d5f939f7ef3c5da627cb48bb6c90bf6c55786203b2358
persistence:
  config:
    enabled: true
    mountPath: /config
  searchlocation:
    enabled: true
    mountPath: /root
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8322
        protocol: tcp
        targetPort: 8080
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            GUAC_PASS: ""
            GUAC_USER: ""
