image:
  repository: stonith404/pingvin-share
  pullPolicy: IfNotPresent
  tag: v1.6.1@sha256:709266ee78dcda17e693e265a2ced8c5ff62b059ab85002edd49d7376942eb5d

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 3333
        port: 3333

persistence:
  data:
    enabled: true
    mountPath: "/opt/app/backend/data"
  image:
    enabled: true
    mountPath: "/opt/app/frontend/public/img"

portal:
  open:
    enabled: true
