image:
  pullPolicy: IfNotPresent
  repository: lscr.io/linuxserver/cops
  tag: 3.4.6@sha256:9c5ea1c83bbd3f57621352fad48d6d588d1bb2f7809749505958e9d1971a8e2f
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10609
        protocol: http
        targetPort: 80
persistence:
  config:
    enabled: true
    mountPath: /config
  books:
    enabled: true
    mountPath: /books
portal:
  open:
    enabled: true
