image:
  repository: itzg/mc-router
  pullPolicy: IfNotPresent
  tag: 1.39.0@sha256:b5e4bb0178d4e200a832b3ab20d99de71040db1c9081d3a8f83c9c47540447b2
service:
  main:
    ports:
      main:
        port: 25564
  minecraft:
    enabled: true
    ports:
      minecraft:
        enabled: true
        port: 25565
mcrouter:
  host_minecraft: []
  #  - "minecraft.local=minecraft-java.ix-minecraft-java.svc.cluster.local:25565"
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          envFrom:
            - secretRef:
                name: "secrets"
          env:
            API_BINDING: ":{{ .Values.service.main.ports.main.port }}"
            PORT: "{{ .Values.service.minecraft.ports.minecraft.port }}"
portal:
  open:
    enabled: false
