image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/ich777/vintagestory
  tag: latest@sha256:da9d1b7d1a0c4df84f697a81e3acec2f6b6c696ef23220dcaa6ee057e704d74e
persistence:
  serverfiles:
    enabled: true
    mountPath: /vintagestory
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 42420
        protocol: tcp
        targetPort: 42420
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            GAME_PARAMS: ""
            VS_CHANNEL: stable@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
