image:
  pullPolicy: IfNotPresent
  repository: adminer
  tag: latest@sha256:e9b9d15a073167b5b2913c6cb0919e65dbe66afa2a897d4fa481c8575a9fe120
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env:
            ADMINER_DESIGN: ""
            ADMINER_PLUGINS: ""
service:
  main:
    ports:
      main:
        port: 18080
        protocol: http
        targetPort: 8080
portal:
  open:
    enabled: true
