image:
  pullPolicy: IfNotPresent
  repository: docker.io/mikenye/tar1090
  tag: latest@sha256:7e567a4ceb2415aadb3a181da2acd34d28ed47fcf8ed3ccc0492202476dc8c5a
persistence: {}
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8078
        protocol: tcp
        targetPort: 80
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            BEASTHOST: <BEASTHOST>
            LAT: xx.xxxxx
            LONG: xx.xxxxx
            MLATHOST: <MLATHOST>
