image:
  repository: ghcr.io/linuxserver/oscam
  pullPolicy: IfNotPresent
  tag: 11893-ls144@sha256:9a87ae34bd6f2f461a4c8833d7eaad0290a70e6502c31f4f3b69ab1b0f61c0f2
service:
  main:
    ports:
      main:
        port: 10062
        targetPort: 8888
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 20
