image:
  repository: wiserain/flexget
  pullPolicy: IfNotPresent
  tag: 3.13.2@sha256:31564940f17e0b711e180277a94254be7756cb89f72b19ef623f3dc9e05f435f
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env:
            FG_LOG_LEVEL: info
            FG_LOG_FILE: flexget.log
            FG_WEBUI_PASSWD: "jLeT78KBDPW"
service:
  main:
    ports:
      main:
        port: 10174
        targetPort: 5050
persistence:
  config:
    enabled: true
    mountPath: /config
  data:
    enabled: true
    mountPath: /data
portal:
  open:
    enabled: true
