image:
  repository: portainer/portainer-ce
  tag: 2.25.0@sha256:7a54433da2d375c7a2ffdf0bddab9d240fc7c4167dad830d0bd244a001419bb8
  pullPolicy: IfNotPresent
beImage:
  repository: portainer/portainer-ee
  tag: 2.25.0@sha256:0f5d382484ce21fbc9e81e4e40a890631339137f69bedcdeb656f5d839f4756a
  pullPolicy: IfNotPresent
portainer:
  # Logo URL
  logo: ""
  # Enables Edge Compute Features
  edge_compute: false
  # Sets Snapshot interval
  snapshot_interval: 5m
  hide_labels:
  # - label1=value1
  # - label2=value2
serviceAccount:
  main:
    enabled: true
    primary: true
rbac:
  main:
    enabled: true
    primary: true
    clusterWide: true
    rules:
      - apiGroups:
          - "*"
        resources:
          - "*"
        verbs:
          - "*"
service:
  main:
    ports:
      main:
        port: 10400
        protocol: https
        targetPort: 9443
  edge:
    enabled: true
    ports:
      edge:
        enabled: true
        port: 10401
        targetPort: 10401
persistence:
  data:
    enabled: true
    mountPath: "/data"
  cache:
    enabled: true
    mountPath: "/.cache"
    type: emptyDir
portal:
  open:
    enabled: true
workload:
  main:
    podSpec:
      automountServiceAccountToken: true
      containers:
        main:
          imageSelector: image
          probes:
            liveness:
              port: 9443
              type: https
            readiness:
              port: 9443
              type: https
            startup:
              port: 9443
              type: https
updated: true
