image:
  pullPolicy: IfNotPresent
  repository: docker.io/hauxir/imgpush
  tag: latest@sha256:eca548e354877f6af4660f87976cda4925f4a69ecf6f716af1644ccab88c9a66
persistence:
  storagecache:
    enabled: true
    mountPath: /cache
  storageimages:
    enabled: true
    mountPath: /images
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 5000
        protocol: tcp
        targetPort: 5000
