image:
  repository: ghcr.io/linuxserver/openvscode-server
  pullPolicy: IfNotPresent
  tag: 1.96.0@sha256:d63f75fed642dab0d350b147b057ef9ef7d3ca92984c01d5aef7ff78b1edfecd
# secretEnv:
#   CONNECTION_TOKEN: "somerandomstring"
#   CONNECTION_SECRET: ""
#   SUDO_PASSWORD: ""
service:
  main:
    ports:
      main:
        targetPort: 3000
        port: 10135
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
