image:
  repository: quay.io/pussthecatorg/rimgo
  tag: latest@sha256:68aef6d690e9b7f611cbf7263ebfdfa1f5b2e0e5818a35aece13c0a43da8ea7a
  pullPolicy: IfNotPresent
persistence: {}

env:
  ADDRESS: 0.0.0.0
  IMGUR_CLIENT_ID: 546c25a59c58ad7
  FORCE_WEBP: "0"

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 3000
        protocol: tcp
        targetPort: 3000

portal:
  open:
    enabled: true
