image:
  repository: quay.io/pussthecatorg/rimgo
  tag: latest@sha256:775b1a00a94d5200951e790ac15c18c85725d976b7e4f578a15b5582154e6b9c
  pullPolicy: IfNotPresent
persistence: {}

env:
  ADDRESS: 0.0.0.0
  IMGUR_CLIENT_ID: 546c25a59c58ad7
  FORCE_WEBP: "0"

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 3000
        protocol: tcp
        targetPort: 3000

portal:
  open:
    enabled: true
