image:
  repository: quay.io/pussthecatorg/rimgo
  tag: latest@sha256:04fa08aa0c4a9e5d3263ce76512fee0b9792a7ccf58de5f85d6f16cfdd553a05
  pullPolicy: IfNotPresent
persistence: {}

env:
  ADDRESS: 0.0.0.0
  IMGUR_CLIENT_ID: 546c25a59c58ad7
  FORCE_WEBP: "0"

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 3000
        protocol: tcp
        targetPort: 3000

portal:
  open:
    enabled: true
