image:
  repository: ghcr.io/elfhosted/nzbhydra2
  pullPolicy: IfNotPresent
  tag: 8.2.3@sha256:e586fccaa57a73adb105e441e40292ac4c6af341c0461b3ba28c1c0f542cde93
service:
  main:
    ports:
      main:
        port: 5076
        targetPort: 5076
persistence:
  config:
    enabled: true
    mountPath: "/config"
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              custom: true
              enabled: true
              spec:
                failureThreshold: 5
                httpGet:
                  path: /actuator/health/livenessState
                  port: main
                initialDelaySeconds: 30
                periodSeconds: 10
                timeoutSeconds: 10
            readiness:
              custom: true
              enabled: true
              spec:
                failureThreshold: 5
                httpGet:
                  path: /actuator/health/readinessState
                  port: main
                initialDelaySeconds: 30
                periodSeconds: 10
                timeoutSeconds: 10
            startup:
              custom: true
              enabled: true
              spec:
                failureThreshold: 5
                httpGet:
                  path: /actuator/health/readinessState
                  port: main
                initialDelaySeconds: 30
                periodSeconds: 10
                timeoutSeconds: 10
