image:
  repository: docker.io/gabekangas/owncast
  tag: 0.2.1@sha256:85265daa3d74c73d67c870c9a5a2ff2769b62493a64676762e8ebf647d3d2eaa
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10088
        targetPort: 8080
  rtmp:
    enabled: true
    # externalTrafficPolicy: Local
    ports:
      rtmp:
        enabled: true
        port: 1935
        targetPort: 1935
persistence:
  config:
    enabled: true
    mountPath: "/app/data"
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
