image:
  repository: docker.io/louislam/uptime-kuma
  pullPolicy: IfNotPresent
  tag: 1.23.17-debian@sha256:0e192c54160b6e3a799dd1ebf4178430fc630a41cd1b6889a148e0e472494a55
security:
  PUID: 0
service:
  main:
    ports:
      main:
        port: 3001
persistence:
  config:
    enabled: true
    mountPath: "/app/data"
portal:
  open:
    enabled: true
metrics:
  main:
    enabled: true
    type: "servicemonitor"
    endpoints:
      - port: main
        path: /metrics
    prometheusRule:
      enabled: false
securityContext:
  container:
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            UPTIME_KUMA_PORT: "{{ .Values.service.main.ports.main.port }}"
