annotations:
  artifacthub.io/category: integration-delivery
  artifacthub.io/license: BUSL-1.1
  artifacthub.io/links: |
    - name: support
      url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/category: unsorted
  truecharts.org/max_helm_version: "3.15"
  truecharts.org/min_helm_version: "3.11"
  truecharts.org/train: library
apiVersion: v2
appVersion: "1.10.4"
dependencies: []
deprecated: false
description: Function library for TrueCharts
home: https://github.com/hey101/charts/library/common
icon: https://truecharts.org/img/hotlink-ok/chart-icons/common.webp
keywords:
  - truecharts
  - library-chart
  - common
kubeVersion: '>=1.24.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: common
sources:
  - https://github.com/hey101/charts/tree/master/charts/library/common
  - https://github.com/truecharts/charts/tree/master/charts/library/common
  - https://ghcr.io/cloudnative-pg/postgis
  - https://ghcr.io/cloudnative-pg/postgresql
  - https://ghcr.io/tensorchord/cloudnative-pgvecto.rs
  - https://ghcr.io/traefik/whoami
  - https://hub.docker.com/_/
  - https://hub.docker.com/r/mikefarah/yq
type: library
version: 25.4.7
