image:
  repository: ghcr.io/elfhosted/emby
  pullPolicy: IfNotPresent
  tag: 4.9.1.8@sha256:fc1795de7de10fd1569f2028232625fb5ed011ca0cd1107f3bd3a7011b6025cf
securityContext:
  container:
    readOnlyRootFilesystem: false
service:
  main:
    ports:
      main:
        port: 10079
        targetPort: 8096
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env: {}
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
