image:
  repository: ghcr.io/elfhosted/emby
  pullPolicy: IfNotPresent
  tag: 4.9.1.9@sha256:5cbba938056eb9bec182db1ede7787769a3c904e9253dda56b7dd0917d2772d2
securityContext:
  container:
    readOnlyRootFilesystem: false
service:
  main:
    ports:
      main:
        port: 10079
        targetPort: 8096
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env: {}
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
