image:
  pullPolicy: IfNotPresent
  repository: yourls
  tag: latest@sha256:a0c44b0296d94d7192ac9d126a3b645aaa08c9b2536568c1073435e77bfb526e
persistence: {}
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 80
        protocol: tcp
        targetPort: 80
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            YOURLS_DB_HOST: ""
            YOURLS_DB_NAME: ""
            YOURLS_DB_PASS: ""
            YOURLS_HOURS_OFFSET: ""
            YOURLS_PASS: ""
            YOURLS_PRIVATE: ""
            YOURLS_SITE: ""
            YOURLS_USER: ""
