image:
  repository: tccr.io/tccr/alpine
  pullPolicy: IfNotPresent
  tag: latest@sha256:a1d1977752c09046b44905a8ceea301820b4cdba1d7097a41f0aaca0d390522c

service:
  main:
    enabled: false
    ports:
      main:
        enabled: false

workload:
  main:
    enabled: false

portal:
  open:
    enabled: false

operator:
  register: true

manifestManager:
  enabled: false
