image:
  repository: cloudflare/cloudflared
  pullPolicy: IfNotPresent
  tag: 2024.12.1@sha256:fc6afe4a5dcf2a801b39fcd538c9d5d4d53ea229fe9976584835bdb8c185ed5d
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          args:
            - tunnel
            - --no-autoupdate
            - run
          env:
            TUNNEL_TOKEN: ""
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
portal:
  open:
    enabled: false
