image:
  repository: ghcr.io/linuxserver/calibre
  tag: 8.11.0@sha256:3a9c05f7cf1fe93ddb1c78595b936a3fc6331b8a0af4474262b06cd2516027e8
  pullPolicy: IfNotPresent
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 8084
        protocol: http
        targetPort: 8080
  webserver:
    enabled: true
    ports:
      webserver:
        enabled: true
        port: 8081
        protocol: http
        targetPort: 8081
ingress:
  webserver:
    enabled: false
    targetSelector:
      webserver: webserver
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            CLI_ARGS:
            PASSWORD: ""
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
