image:
  repository: ghcr.io/linuxserver/healthchecks
  tag: 3.8.20241209@sha256:5eb4f30b8b8d039f823c2b01b4a3072b59e02b414d2eb6b1c90c5e9a51b465a6
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10074
        targetPort: 8000
persistence:
  config:
    enabled: true
    mountPath: "/config"
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp
          env:
            REGENERATE_SETTINGS: "True"
            SITE_ROOT: "https://healthchecks.domain"
            SITE_NAME: ""
            SUPERUSER_EMAIL: "email@healthchecks.io"
            SUPERUSER_PASSWORD: "myVeryStrongPassword"
